wandb_version: 1

M:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1675958426.364701
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 5
batch_size:
  desc: null
  value: 200
configfile:
  desc: null
  value: CHANNEL_CONFIG_INTERPOLATED.json
episode_size:
  desc: null
  value: 1000
epsilon:
  desc: null
  value: 0.5
gamma:
  desc: null
  value: 0.95
k_path:
  desc: null
  value: 3
layer_size:
  desc: null
  value: 128
num_layers:
  desc: null
  value: 5
regu_scalar:
  desc: null
  value: 0.0001
slot_total:
  desc: null
  value: 100
